// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen_DP
void ui_Screen_DP_screen_init(void);
lv_obj_t * ui_Screen_DP;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label17;
void ui_event_Switch_Power_Chatcnc(lv_event_t * e);
lv_obj_t * ui_Switch_Power_Chatcnc;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Image5;
lv_obj_t * ui_image_Status;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label2;
void ui_event_Switch_Power_Xiaomi1(lv_event_t * e);
lv_obj_t * ui_Switch_Power_Xiaomi1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Image8;
lv_obj_t * ui_image_Status1;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label10;
void ui_event_Switch_Power_Xiaomi(lv_event_t * e);
lv_obj_t * ui_Switch_Power_Xiaomi;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Image4;
lv_obj_t * ui_image_Status2;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label19;
void ui_event_Slider_Brightness_Light_Chatcnc(lv_event_t * e);
lv_obj_t * ui_Slider_Brightness_Light_Chatcnc;
void ui_event_Switch_Power_Light_Chatcnc(lv_event_t * e);
lv_obj_t * ui_Switch_Power_Light_Chatcnc;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Image6;
lv_obj_t * ui_image_Status3;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label13;
void ui_event_Switch_Power_Ender(lv_event_t * e);
lv_obj_t * ui_Switch_Power_Ender;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Image3;
lv_obj_t * ui_image_Status4;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label1;
void ui_event_Slider_Brightness_Light_Ender(lv_event_t * e);
lv_obj_t * ui_Slider_Brightness_Light_Ender;
void ui_event_Switch_Power_Light_Ender(lv_event_t * e);
lv_obj_t * ui_Switch_Power_Light_Ender;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Image2;
lv_obj_t * ui_image_Status5;
lv_obj_t * ui_Label12;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Switch_Power_Chatcnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_switch_power_chatcnc(e);
    }
}
void ui_event_Switch_Power_Xiaomi1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_switch_power_xiaomi(e);
    }
}
void ui_event_Switch_Power_Xiaomi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_switch_power_xiaomi(e);
    }
}
void ui_event_Slider_Brightness_Light_Chatcnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_slider_brightness_chatcnc(e);
    }
}
void ui_event_Switch_Power_Light_Chatcnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_switch_power_light_chatcnc(e);
    }
}
void ui_event_Switch_Power_Ender(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_switch_power_ender(e);
    }
}
void ui_event_Slider_Brightness_Light_Ender(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_slider_brightness_ender(e);
    }
}
void ui_event_Switch_Power_Light_Ender(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_switch_power_light_ender(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_DP_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_DP);
}
