// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen_DP
void ui_Screen_DP_screen_init(void);
extern lv_obj_t * ui_Screen_DP;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label17;
void ui_event_Switch_Power_Chatcnc(lv_event_t * e);
extern lv_obj_t * ui_Switch_Power_Chatcnc;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_image_Status;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label2;
void ui_event_Switch_Power_Xiaomi1(lv_event_t * e);
extern lv_obj_t * ui_Switch_Power_Xiaomi1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_image_Status1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label10;
void ui_event_Switch_Power_Xiaomi(lv_event_t * e);
extern lv_obj_t * ui_Switch_Power_Xiaomi;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_image_Status2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label19;
void ui_event_Slider_Brightness_Light_Chatcnc(lv_event_t * e);
extern lv_obj_t * ui_Slider_Brightness_Light_Chatcnc;
void ui_event_Switch_Power_Light_Chatcnc(lv_event_t * e);
extern lv_obj_t * ui_Switch_Power_Light_Chatcnc;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_image_Status3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label13;
void ui_event_Switch_Power_Ender(lv_event_t * e);
extern lv_obj_t * ui_Switch_Power_Ender;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_image_Status4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label1;
void ui_event_Slider_Brightness_Light_Ender(lv_event_t * e);
extern lv_obj_t * ui_Slider_Brightness_Light_Ender;
void ui_event_Switch_Power_Light_Ender(lv_event_t * e);
extern lv_obj_t * ui_Switch_Power_Light_Ender;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_image_Status5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_549405571);    // assets\chat-cnc-s.png
LV_IMG_DECLARE(ui_img_581727398);    // assets\red-circle.png
LV_IMG_DECLARE(ui_img_769470371);    // assets\einhell-s.png
LV_IMG_DECLARE(ui_img_1869445265);    // assets\Xiaomi-s.png
LV_IMG_DECLARE(ui_img_1822783234);    // assets\diffusor-s.png
LV_IMG_DECLARE(ui_img_538830638);    // assets\ender-3-pro-s.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
