// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"

void event_switch_power_chatcnc(lv_event_t * e)
{
	// Your code here
}

void event_slider_brightness_chatcnc(lv_event_t * e)
{
	// Your code here
}

void event_switch_power_light_chatcnc(lv_event_t * e)
{
	// Your code here
}

void event_switch_power_xiaomi(lv_event_t * e)
{
	// Your code here
}

void event_switch_power_ender(lv_event_t * e)
{
	// Your code here
}

void event_slider_brightness_ender(lv_event_t * e)
{
	// Your code here
}

void event_switch_power_light_ender(lv_event_t * e)
{
	// Your code here
}

void event_slider_speed_alveo3d(lv_event_t * e)
{
	// Your code here
}

void event_power_alveo3d(lv_event_t * e)
{
	// Your code here
}
