// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_DP_screen_init(void)
{
    ui_Screen_DP = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_DP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Screen_DP);
    lv_obj_set_width(ui_Panel4, 800);
    lv_obj_set_height(ui_Panel4, 500);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Panel4, LV_DIR_HOR);

    ui_Panel13 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel13, 250);
    lv_obj_set_height(ui_Panel13, 440);
    lv_obj_set_x(ui_Panel13, -176);
    lv_obj_set_y(ui_Panel13, 40);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -67);
    lv_obj_set_y(ui_Label17, 114);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Power");

    ui_Switch_Power_Chatcnc = lv_switch_create(ui_Panel13);
    lv_obj_set_width(ui_Switch_Power_Chatcnc, 50);
    lv_obj_set_height(ui_Switch_Power_Chatcnc, 25);
    lv_obj_set_x(ui_Switch_Power_Chatcnc, 66);
    lv_obj_set_y(ui_Switch_Power_Chatcnc, 113);
    lv_obj_set_align(ui_Switch_Power_Chatcnc, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch_Power_Chatcnc, LV_STATE_CHECKED);       /// States

    ui_Label18 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, -180);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Chat CNC");

    ui_Image5 = lv_img_create(ui_Panel13);
    lv_img_set_src(ui_Image5, &ui_img_549405571);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -2);
    lv_obj_set_y(ui_Image5, -9);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 200);

    ui_Label_Leistung = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label_Leistung, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Leistung, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Leistung, 79);
    lv_obj_set_y(ui_Label_Leistung, 37);
    lv_label_set_text(ui_Label_Leistung, "625W");
    lv_obj_set_style_text_font(ui_Label_Leistung, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image_Status6 = lv_img_create(ui_Panel13);
    lv_img_set_src(ui_image_Status6, &ui_img_581727398);
    lv_obj_set_width(ui_image_Status6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_Status6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image_Status6, -87);
    lv_obj_set_y(ui_image_Status6, 141);
    lv_obj_set_align(ui_image_Status6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image_Status6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_image_Status6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_image_Status6, 150);

    ui_Label4 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -46);
    lv_obj_set_y(ui_Label4, 142);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Offline");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel1, 250);
    lv_obj_set_height(ui_Panel1, 440);
    lv_obj_set_x(ui_Panel1, -176);
    lv_obj_set_y(ui_Panel1, 40);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Leistung1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label_Leistung1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Leistung1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Leistung1, 79);
    lv_obj_set_y(ui_Label_Leistung1, 37);
    lv_label_set_text(ui_Label_Leistung1, "1250W");
    lv_obj_set_style_text_font(ui_Label_Leistung1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -68);
    lv_obj_set_y(ui_Label2, 113);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Power");

    ui_Switch_Power_Xiaomi1 = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_Switch_Power_Xiaomi1, 50);
    lv_obj_set_height(ui_Switch_Power_Xiaomi1, 25);
    lv_obj_set_x(ui_Switch_Power_Xiaomi1, 64);
    lv_obj_set_y(ui_Switch_Power_Xiaomi1, 115);
    lv_obj_set_align(ui_Switch_Power_Xiaomi1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch_Power_Xiaomi1, LV_STATE_CHECKED);       /// States

    ui_Label3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -180);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Staubsauger");

    ui_Image8 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image8, &ui_img_769470371);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, -4);
    lv_obj_set_y(ui_Image8, -25);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 200);

    ui_image_Status1 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_image_Status1, &ui_img_581727398);
    lv_obj_set_width(ui_image_Status1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_Status1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image_Status1, -87);
    lv_obj_set_y(ui_image_Status1, 141);
    lv_obj_set_align(ui_image_Status1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image_Status1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_image_Status1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_image_Status1, 150);

    ui_Label6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -46);
    lv_obj_set_y(ui_Label6, 142);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Offline");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel9, 250);
    lv_obj_set_height(ui_Panel9, 440);
    lv_obj_set_x(ui_Panel9, -176);
    lv_obj_set_y(ui_Panel9, 40);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -68);
    lv_obj_set_y(ui_Label10, 113);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Power");

    ui_Switch_Power_Xiaomi = lv_switch_create(ui_Panel9);
    lv_obj_set_width(ui_Switch_Power_Xiaomi, 50);
    lv_obj_set_height(ui_Switch_Power_Xiaomi, 25);
    lv_obj_set_x(ui_Switch_Power_Xiaomi, 64);
    lv_obj_set_y(ui_Switch_Power_Xiaomi, 115);
    lv_obj_set_align(ui_Switch_Power_Xiaomi, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch_Power_Xiaomi, LV_STATE_CHECKED);       /// States

    ui_Label11 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -180);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Luftfilter");

    ui_Image4 = lv_img_create(ui_Panel9);
    lv_img_set_src(ui_Image4, &ui_img_1869445265);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 3);
    lv_obj_set_y(ui_Image4, -11);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 150);

    ui_image_Status2 = lv_img_create(ui_Panel9);
    lv_img_set_src(ui_image_Status2, &ui_img_581727398);
    lv_obj_set_width(ui_image_Status2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_Status2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image_Status2, -87);
    lv_obj_set_y(ui_image_Status2, 141);
    lv_obj_set_align(ui_image_Status2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image_Status2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_image_Status2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_image_Status2, 150);

    ui_Label7 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -46);
    lv_obj_set_y(ui_Label7, 142);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Offline");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Leistung3 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label_Leistung3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Leistung3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Leistung3, 79);
    lv_obj_set_y(ui_Label_Leistung3, 37);
    lv_label_set_text(ui_Label_Leistung3, "33W");
    lv_obj_set_style_text_font(ui_Label_Leistung3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel14, 250);
    lv_obj_set_height(ui_Panel14, 440);
    lv_obj_set_x(ui_Panel14, -176);
    lv_obj_set_y(ui_Panel14, 40);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Leistung4 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label_Leistung4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Leistung4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Leistung4, 90);
    lv_obj_set_y(ui_Label_Leistung4, 37);
    lv_label_set_text(ui_Label_Leistung4, "5W");
    lv_obj_set_style_text_font(ui_Label_Leistung4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -67);
    lv_obj_set_y(ui_Label19, 113);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Power");

    ui_Switch_Power_Light_Chatcnc = lv_switch_create(ui_Panel14);
    lv_obj_set_width(ui_Switch_Power_Light_Chatcnc, 50);
    lv_obj_set_height(ui_Switch_Power_Light_Chatcnc, 25);
    lv_obj_set_x(ui_Switch_Power_Light_Chatcnc, 66);
    lv_obj_set_y(ui_Switch_Power_Light_Chatcnc, 114);
    lv_obj_set_align(ui_Switch_Power_Light_Chatcnc, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch_Power_Light_Chatcnc, LV_STATE_CHECKED);       /// States

    ui_Label20 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, -180);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Licht");

    ui_Image6 = lv_img_create(ui_Panel14);
    lv_img_set_src(ui_Image6, &ui_img_1822783234);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, -3);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 200);

    ui_image_Status3 = lv_img_create(ui_Panel14);
    lv_img_set_src(ui_image_Status3, &ui_img_581727398);
    lv_obj_set_width(ui_image_Status3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_Status3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image_Status3, -87);
    lv_obj_set_y(ui_image_Status3, 141);
    lv_obj_set_align(ui_image_Status3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image_Status3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_image_Status3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_image_Status3, 150);

    ui_Label8 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -46);
    lv_obj_set_y(ui_Label8, 142);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Offline");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel11, 250);
    lv_obj_set_height(ui_Panel11, 440);
    lv_obj_set_x(ui_Panel11, -176);
    lv_obj_set_y(ui_Panel11, 40);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Leistung5 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label_Leistung5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Leistung5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Leistung5, 79);
    lv_obj_set_y(ui_Label_Leistung5, 37);
    lv_label_set_text(ui_Label_Leistung5, "120W");
    lv_obj_set_style_text_font(ui_Label_Leistung5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -67);
    lv_obj_set_y(ui_Label13, 120);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Power");

    ui_Switch_Power_Ender = lv_switch_create(ui_Panel11);
    lv_obj_set_width(ui_Switch_Power_Ender, 50);
    lv_obj_set_height(ui_Switch_Power_Ender, 25);
    lv_obj_set_x(ui_Switch_Power_Ender, 65);
    lv_obj_set_y(ui_Switch_Power_Ender, 120);
    lv_obj_set_align(ui_Switch_Power_Ender, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch_Power_Ender, LV_STATE_CHECKED);       /// States

    ui_Label16 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -180);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Ender 3 Pro");

    ui_Image3 = lv_img_create(ui_Panel11);
    lv_img_set_src(ui_Image3, &ui_img_538830638);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, -22);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 200);

    ui_image_Status4 = lv_img_create(ui_Panel11);
    lv_img_set_src(ui_image_Status4, &ui_img_581727398);
    lv_obj_set_width(ui_image_Status4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_Status4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image_Status4, -87);
    lv_obj_set_y(ui_image_Status4, 141);
    lv_obj_set_align(ui_image_Status4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image_Status4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_image_Status4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_image_Status4, 150);

    ui_Label9 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -46);
    lv_obj_set_y(ui_Label9, 142);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Offline");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel3, 250);
    lv_obj_set_height(ui_Panel3, 440);
    lv_obj_set_x(ui_Panel3, -176);
    lv_obj_set_y(ui_Panel3, 40);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Leistung2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label_Leistung2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Leistung2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Leistung2, 90);
    lv_obj_set_y(ui_Label_Leistung2, 37);
    lv_label_set_text(ui_Label_Leistung2, "5W");
    lv_obj_set_style_text_font(ui_Label_Leistung2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -68);
    lv_obj_set_y(ui_Label1, 120);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Power");

    ui_Switch_Power_Light_Ender = lv_switch_create(ui_Panel3);
    lv_obj_set_width(ui_Switch_Power_Light_Ender, 50);
    lv_obj_set_height(ui_Switch_Power_Light_Ender, 25);
    lv_obj_set_x(ui_Switch_Power_Light_Ender, 73);
    lv_obj_set_y(ui_Switch_Power_Light_Ender, 120);
    lv_obj_set_align(ui_Switch_Power_Light_Ender, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch_Power_Light_Ender, LV_STATE_CHECKED);       /// States

    ui_Label5 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -180);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Licht");

    ui_Image2 = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_Image2, &ui_img_1822783234);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, 5);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 200);

    ui_image_Status5 = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_image_Status5, &ui_img_581727398);
    lv_obj_set_width(ui_image_Status5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_Status5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image_Status5, -87);
    lv_obj_set_y(ui_image_Status5, 141);
    lv_obj_set_align(ui_image_Status5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image_Status5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_image_Status5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_image_Status5, 150);

    ui_Label12 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -46);
    lv_obj_set_y(ui_Label12, 142);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Offline");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Switch_Power_Chatcnc, ui_event_Switch_Power_Chatcnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch_Power_Xiaomi1, ui_event_Switch_Power_Xiaomi1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch_Power_Xiaomi, ui_event_Switch_Power_Xiaomi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch_Power_Light_Chatcnc, ui_event_Switch_Power_Light_Chatcnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch_Power_Ender, ui_event_Switch_Power_Ender, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch_Power_Light_Ender, ui_event_Switch_Power_Light_Ender, LV_EVENT_ALL, NULL);

}
